import { readFileSync } from 'node:fs'
import { createRequire } from 'node:module'
import { basename, dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import type { World } from '@uchronia/core'
import type { Artifact } from '@uchronia/schemas'

function yearLabel(year: number): string {
  return year < 0 ? `${Math.abs(year)} BC` : String(year)
}

// ---------------------------------------------------------------- fonts
// "Self-contained" must include the typography, or every reader without
// these faces installed sees the design fall back to Palatino. The woff2
// files embed as data URIs (≈160 KB once - cached across renders). Resolution
// order: node_modules (dev/tests/Docker, where @fontsource is installed),
// then a fonts/ directory beside this module (the Vercel bundle, where
// copy-vercel-assets.mjs stages the files under dist/fonts). If both miss,
// degrade to the system stacks already present in the CSS rather than fail
// the export.

const requireFromHere = createRequire(import.meta.url)
const hereDir = dirname(fileURLToPath(import.meta.url))

function fontFile(packagePath: string): Buffer | null {
  try {
    return readFileSync(requireFromHere.resolve(packagePath))
  } catch {}
  try {
    return readFileSync(join(hereDir, 'fonts', basename(packagePath)))
  } catch {}
  return null
}

function fontFace(family: string, packagePath: string, style: 'normal' | 'italic'): string {
  const file = fontFile(packagePath)
  if (file === null) return ''
  const data = file.toString('base64')
  return `@font-face{font-family:'${family}';font-style:${style};font-weight:400;font-display:swap;src:url(data:font/woff2;base64,${data}) format('woff2')}`
}

let fontCssCache: string | null = null
function embeddedFontCss(): string {
  if (fontCssCache === null) {
    fontCssCache = [
      fontFace('Spectral', '@fontsource/spectral/files/spectral-latin-400-normal.woff2', 'normal'),
      fontFace('Spectral', '@fontsource/spectral/files/spectral-latin-400-italic.woff2', 'italic'),
      fontFace(
        'IM Fell English',
        '@fontsource/im-fell-english/files/im-fell-english-latin-400-normal.woff2',
        'normal',
      ),
      fontFace(
        'IBM Plex Mono',
        '@fontsource/ibm-plex-mono/files/ibm-plex-mono-latin-400-normal.woff2',
        'normal',
      ),
    ].join('\n')
  }
  return fontCssCache
}

/** F10 - a branch as readable markdown. */
export function renderMarkdown(world: World, branchId: string): string {
  const branch = world.getBranch(branchId)
  const pod = world.pod
  const events = world.resolveEvents(branchId)
  const convergences = new Map(world.resolveConvergences(branchId).map((c) => [c.eventId, c]))
  const lines: string[] = []

  lines.push(`# ${world.timeline.title}`)
  lines.push('')
  lines.push(`*A chronicle of a time that never was - branch: ${branch.name}.*`)
  lines.push('')
  lines.push(`**The divergence (${pod.dateLabel}, ${pod.region}):** ${pod.statement}`)
  lines.push('')
  lines.push(`> The record: ${pod.baselineContext}`)
  if (branch.subPod) {
    lines.push('')
    lines.push(`**This branch's own divergence:** ${branch.subPod.statement}`)
  }
  lines.push('')

  for (const era of world.resolveEras(branchId)) {
    lines.push(`## ${era.title} (${yearLabel(era.startYear)} – ${yearLabel(era.endYear)})`)
    lines.push('')
    lines.push(era.summary)
    if (era.pressures.length > 0) {
      lines.push('')
      lines.push(
        `*Pressures: ${era.pressures.map((p) => `${p.name.toLowerCase()} (${p.kind}, ${p.intensity})`).join(' · ')}*`,
      )
    }
    lines.push('')
    for (const event of events.filter((e) => e.eraId === era.id)) {
      const marks: string[] = [`plausibility ${event.plausibility.score.toFixed(2)}`]
      if (event.wildcard) marks.push('wildcard')
      if (event.flags.convergence) marks.push('◉ convergence')
      if (event.flags.disputed) marks.push('disputed')
      lines.push(`### ${event.date.label} - ${event.title}`)
      lines.push('')
      lines.push(`\`${marks.join(' · ')}\``)
      lines.push('')
      lines.push(event.summary)
      if (event.detail) {
        lines.push('')
        lines.push(event.detail)
      }
      const convergence = convergences.get(event.id)
      if (convergence) {
        lines.push('')
        lines.push(`> ◉ Converges with the record: ${convergence.similarityNote}`)
      }
      if (event.flags.disputed && event.criticNotes) {
        lines.push('')
        lines.push(`> **Disputed - the critic's notes:**`)
        for (const note of event.criticNotes) {
          lines.push(`> - *${note.type}* (${note.severity}): ${note.note}`)
        }
      }
      lines.push('')
    }
  }

  lines.push('---')
  lines.push('')
  lines.push(
    '*Generated by [Uchronia](https://github.com/vignesh-nagarajan-vn/uchronia). Speculative fiction produced by a language model - a thinking toy, not scholarship, and not a source.*',
  )
  return lines.join('\n')
}

function esc(text: string): string {
  return text.replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('>', '&gt;')
}

function artifactHtml(artifact: Artifact): string {
  const body = artifact.body
  switch (body.kind) {
    case 'letter':
      return `<div class="artifact letter"><p class="place">${esc(body.place)}, ${esc(body.dateLabel)}</p><p><em>${esc(body.salutation)}</em></p>${body.paragraphs.map((p) => `<p class="ind"><em>${esc(p)}</em></p>`).join('')}<p class="sig"><em>${esc(body.closing)}</em><br><span class="fell">${esc(body.signature)}</span></p>${body.postscript ? `<p class="ps"><em>${esc(body.postscript)}</em></p>` : ''}</div>`
    case 'newspaper':
      return `<div class="artifact news"><p class="masthead fell">${esc(body.masthead)}</p><p class="dateline">${esc(body.dateline)}</p><p class="headline fell">${esc(body.headline)}</p>${body.subhead ? `<p class="subhead"><em>${esc(body.subhead)}</em></p>` : ''}${body.columns.map((c) => `${c.heading ? `<h4>${esc(c.heading)}</h4>` : ''}${c.paragraphs.map((p) => `<p>${esc(p)}</p>`).join('')}`).join('')}${body.notices.length ? `<div class="notices">${body.notices.map((n) => `<p><em>${esc(n)}</em></p>`).join('')}</div>` : ''}</div>`
    case 'encyclopedia':
      return `<div class="artifact encyc"><p class="masthead fell">${esc(body.encyclopediaTitle)}</p><p class="dateline">${esc(body.editionNote)}</p><h4>${esc(body.headword)}</h4>${body.entryParagraphs.map((p) => `<p>${esc(p)}</p>`).join('')}<p class="dateline">see also: ${body.seeAlso.map(esc).join(' · ')}</p></div>`
    case 'poster':
      return `<div class="artifact poster"><p class="headline fell">${esc(body.headline)}</p>${body.subheadline ? `<p><em>${esc(body.subheadline)}</em></p>` : ''}${body.lines.map((l) => `<p>${esc(l)}</p>`).join('')}${body.slogan ? `<p class="slogan fell">${esc(body.slogan)}</p>` : ''}<p class="dateline">${esc(body.issuer)}</p></div>`
    default:
      return ''
  }
}

/**
 * F10 - a self-contained static HTML edition of one branch: no JS, inlined
 * RED THREAD tokens, a readable artifact in itself.
 */
export function renderStaticHtml(world: World, branchId: string): string {
  const branch = world.getBranch(branchId)
  const pod = world.pod
  const events = world.resolveEvents(branchId)
  const convergences = new Map(world.resolveConvergences(branchId).map((c) => [c.eventId, c]))
  const artifactsByEvent = new Map<string, Artifact[]>()
  for (const event of events) {
    const artifacts = world.artifactsForEvent(event.id)
    if (artifacts.length > 0) artifactsByEvent.set(event.id, artifacts)
  }

  const eraSections = world
    .resolveEras(branchId)
    .map((era, i) => {
      const eraEvents = events.filter((e) => e.eraId === era.id)
      const roman =
        ['I', 'II', 'III', 'IV', 'V', 'VI', 'VII', 'VIII', 'IX', 'X', 'XI', 'XII'][i] ??
        String(i + 1)
      return `<section class="era">
<header><span class="numeral fell">${roman}</span><div><h2>${esc(era.title)} <span class="span">${yearLabel(era.startYear)} – ${yearLabel(era.endYear)}</span></h2><p class="summary">${esc(era.summary)}</p></div></header>
${eraEvents
  .map((event) => {
    const marks = [`plausibility ${event.plausibility.score.toFixed(2)}`]
    if (event.wildcard) marks.push('wildcard')
    const convergence = convergences.get(event.id)
    return `<article class="event">
<p class="date">${esc(event.date.label)}</p>
<div class="body"><h3>${esc(event.title)}</h3>
<p>${esc(event.summary)}</p>
${
  event.detail
    ? event.detail
        .split('\n\n')
        .map((p) => `<p class="detail">${esc(p)}</p>`)
        .join('')
    : ''
}
<p class="marks">${marks.join(' · ')}${event.flags.convergence ? ' · <span class="record">◉ convergence</span>' : ''}${event.flags.disputed ? ' · <span class="thread">disputed</span>' : ''}</p>
${convergence ? `<p class="convergence">◉ ${esc(convergence.similarityNote)}</p>` : ''}
${event.flags.disputed && event.criticNotes ? `<div class="critique"><p class="marks thread">the critic's notes</p>${event.criticNotes.map((n) => `<p><strong>${n.type}</strong> (${n.severity}): ${esc(n.note)}</p>`).join('')}</div>` : ''}
${(artifactsByEvent.get(event.id) ?? []).map(artifactHtml).join('')}
</div></article>`
  })
  .join('\n')}
</section>`
    })
    .join('\n')

  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${esc(world.timeline.title)} · Uchronia</title>
<style>
${embeddedFontCss()}
:root{--paper:#e8eae3;--raised:#eff1eb;--ink:#22261f;--faded:#5c6157;--record:#174a7c;--thread:#a8281a;--rule:#c6cabf}
@media (prefers-color-scheme: dark){:root{--paper:#0f1420;--raised:#161c2b;--ink:#ede8dc;--faded:#a9a395;--record:#7fa9d9;--thread:#d96a55;--rule:#2a3245}}
*{box-sizing:border-box;margin:0}
body{background:var(--paper);color:var(--ink);font:16px/1.65 'Spectral',Georgia,'Times New Roman',serif;padding:48px 20px 96px}
.fell{font-family:'IM Fell English','Iowan Old Style',Palatino,serif}
main{max-width:760px;margin:0 auto}
.wordmark{font-size:40px;text-align:center}
.tag,.dateline,.date,.marks,.span,.place,.mono{font-family:'IBM Plex Mono',ui-monospace,monospace;font-size:12.5px;color:var(--faded)}
.tag{text-align:center;margin-top:4px}
.pod{margin:40px 0 8px;border-left:3px solid var(--thread);padding-left:16px}
.pod .marks{color:var(--thread)}
.pod h1{font-size:22px;line-height:1.35}
.pod .basis{color:var(--faded);font-size:14.5px;margin-top:6px}
.pod .basis b{color:var(--record);font-weight:500;font-family:'IBM Plex Mono',monospace;font-size:12px}
.era{margin-top:44px}
.era header{display:flex;gap:16px;align-items:baseline;border-bottom:1px solid var(--rule);padding-bottom:8px}
.numeral{font-size:42px;color:var(--thread)}
.era h2{font-size:19px}
.era .span{margin-left:10px;font-weight:400}
.era .summary{color:var(--faded);font-size:15px}
.event{display:grid;grid-template-columns:76px 1fr;gap:14px;margin-top:20px;border-left:2px solid var(--thread);padding-left:14px;margin-left:4px}
.event .date{text-align:right;padding-top:3px}
.event h3{font-size:16.5px}
.event .detail{margin-top:8px}
.event .marks{margin-top:6px}
.record{color:var(--record)}
.thread{color:var(--thread)}
.convergence{margin-top:6px;color:var(--record);font-size:14px;border-left:2px solid var(--record);padding-left:10px}
.critique{margin-top:8px;border-left:2px solid var(--thread);padding-left:10px;font-size:14px}
.artifact{background:var(--raised);border:1px solid var(--rule);border-radius:2px;padding:22px 26px;margin-top:14px}
.artifact .masthead{text-align:center;font-size:24px;border-bottom:2px solid var(--ink);padding-bottom:6px}
.artifact .headline{text-align:center;font-size:21px;margin-top:10px}
.artifact .dateline{text-align:center;margin-top:4px}
.artifact h4{margin-top:10px;font-size:14px;text-transform:uppercase;letter-spacing:.04em}
.artifact p{margin-top:8px;font-size:14.5px}
.letter p{font-style:italic}
.letter .ind{text-indent:2em}
.letter .sig{text-align:right}
.letter .sig .fell{font-size:22px}
.letter .ps{border-top:1px solid var(--rule);padding-top:8px;color:var(--faded)}
.poster{text-align:center;border:3px double var(--ink)}
.poster .headline{font-size:30px}
.poster .slogan{color:var(--thread);font-size:20px;margin-top:14px}
.notices{border-top:2px solid var(--rule);margin-top:12px;padding-top:8px}
.notices p{font-size:12.5px;border:1px solid var(--rule);padding:6px 8px}
footer{margin-top:56px;border-top:1px solid var(--rule);padding-top:12px;font-size:12.5px;color:var(--faded);text-align:center}
</style>
</head>
<body>
<main>
<p class="wordmark fell">Uchronia</p>
<p class="tag">a chronicle of a time that never was · branch: ${esc(branch.name)}</p>
<div class="pod">
<p class="marks">the divergence · ${esc(pod.dateLabel)} · ${esc(pod.region)}</p>
<h1>${esc(pod.statement)}</h1>
<p class="basis"><b>the record:</b> ${esc(pod.baselineContext)}</p>
${branch.subPod ? `<p class="basis"><b class="thread">this branch:</b> ${esc(branch.subPod.statement)}</p>` : ''}
</div>
${eraSections}
<footer>Speculative fiction produced by a language model - a thinking toy, not scholarship, and not a source.<br>Uchronia · ${new Date(world.timeline.createdAt).toISOString().slice(0, 10)}</footer>
</main>
</body>
</html>`
}
